namespace: voting

images:
  pullPolicy: IfNotPresent

vote:
  name: vote
  replicas: 1
  image: ghcr.io/nugusu20/vote
  tag: 6530efac3c2a8cfe5d34c1db8127e7781ba02782
  service:
    port: 80
    targetPort: 80

result:
  name: result
  replicas: 1
  image: ghcr.io/nugusu20/result
  tag: 6530efac3c2a8cfe5d34c1db8127e7781ba02782
  service:
    port: 80
    targetPort: 80

worker:
  name: worker
  replicas: 1
  image: ghcr.io/nugusu20/worker
  tag: 6530efac3c2a8cfe5d34c1db8127e7781ba02782

redis:
  name: redis
  replicas: 1
  image: redis
  tag: alpine
  service:
    port: 6379
    targetPort: 6379

postgres:
  name: db
  image: postgres
  tag: 15-alpine
  service:
    port: 5432
    targetPort: 5432
  auth:
    user: postgres
    password: postgres
    database: postgres
  storage:
    size: 1Gi
