apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.vote.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote.name }}
    spec:
      containers:
        - name: {{ .Values.vote.name }}
          image: "{{ .Values.vote.image }}:{{ .Values.vote.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          ports:
            - containerPort: {{ .Values.vote.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vote.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.vote.name }}
  ports:
    - port: {{ .Values.vote.service.port }}
      targetPort: {{ .Values.vote.service.targetPort }}
